cursor {{colors.on_surface.default.hex}}
cursor_text_color {{colors.on_surface_variant.default.hex}}

foreground            {{colors.on_surface.default.hex}}
background            {{colors.surface.default.hex}}
selection_foreground  {{colors.on_secondary.default.hex}}
selection_background  {{colors.secondary_fixed_dim.default.hex}}
url_color             {{colors.primary.default.hex}}


color0  {{colors.on_surface.default.hex}}
color8  {{colors.on_surface_variant.default.hex}}

color1  {{colors.error.default.hex | set_saturation: 20 | set_lightness: 70}}
color9  {{colors.error.default.hex | set_saturation: 95}}

color2  {{colors.primary.default.hex | set_saturation: 20 | set_lightness: 70}}
color10 {{colors.primary_fixed.default.hex | set_saturation: 95}}

color3  {{colors.secondary.default.hex | set_saturation: 20 | set_lightness: 70}}
color11 {{colors.secondary_fixed.default.hex | set_saturation: 95}}

color4  {{colors.tertiary.default.hex | set_saturation: 20 | set_lightness: 70}}
color12 {{colors.tertiary_fixed.default.hex | set_saturation: 95}}

color5  {{colors.tertiary_fixed.default.hex | set_saturation: 20 | set_lightness: 70}}
color13 {{colors.tertiary_fixed_dim.default.hex | set_saturation: 95}}

color6  {{colors.secondary_fixed.default.hex | set_saturation: 20 | set_lightness: 70}}
color14 {{colors.secondary_fixed_dim.default.hex | set_saturation: 95}}

color7  {{colors.surface_container_low.default.hex | set_saturation: 20 | set_lightness: 70}}
color15 {{colors.surface_container_highest.default.hex | set_saturation: 95}}
