cursor #dde4e4
cursor_text_color #bec8c9

foreground            #dde4e4
background            #0e1415
selection_foreground  #1b3436
selection_background  #b1cbce
url_color             #80d4db


color0  #dde4e4
color8  #bec8c9

color1  #c2a6a3
color9  #fdb6ad

color2  #a3bfc2
color10 #98f5fc

color3  #a3bfc2
color11 #b9f9fd

color4  #a3adc2
color12 #d8e3fe

color5  #a3acc2
color13 #a4c0fd

color6  #a3c0c2
color14 #83effc

color7  #a3c2c2
color15 #036363
